import React, { useCallback, useEffect, useMemo, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { customFetch } from '@workspace/api-client-react';
import colors from '@/constants/colors';
const c=colors.light, KEY='tradiqs.notifications.read.v1';
type Notification={id:string;title:'New Trade Setup';message:string;type:'AI_ALERT';timestamp:number;referenceId:string};
const relative=(timestamp:number)=>{const ms=timestamp<1e11?timestamp*1000:timestamp;const minutes=Math.max(0,Math.floor((Date.now()-ms)/60000));return minutes<60?`${minutes||1}m ago`:minutes<1440?`${Math.floor(minutes/60)}h ago`:`${Math.floor(minutes/1440)}d ago`;};
export default function NotificationsScreen(){
 const router=useRouter();const [items,setItems]=useState<Notification[]>([]);const [loading,setLoading]=useState(true);const [failed,setFailed]=useState(false);const [read,setRead]=useState<string[]>([]);
 const load=useCallback(async()=>{setLoading(true);setFailed(false);try{const data=await customFetch<Notification[]>('/api/notifications');setItems(Array.isArray(data)?data:[]);}catch{setItems([]);setFailed(true);}finally{setLoading(false);}},[]);
 useEffect(()=>{AsyncStorage.getItem(KEY).then(raw=>raw&&setRead(JSON.parse(raw))).catch(()=>{});void load();},[load]);
 const unread=useMemo(()=>items.filter(item=>!read.includes(item.id)).length,[items,read]);const mark=(id:string)=>{const next=[...new Set([...read,id])];setRead(next);AsyncStorage.setItem(KEY,JSON.stringify(next)).catch(()=>{});};const openSignalDesk=()=>{router.dismiss();setTimeout(()=>router.navigate('/signals' as never),0);};
 return <View style={s.page}><View style={s.header}><View><Text style={s.title}>Notifications</Text><Text style={s.subtitle}>{unread?`${unread} Unread Alerts`:'All caught up'}</Text></View><TouchableOpacity onPress={()=>router.back()} accessibilityLabel="Close notifications"><Feather name="x" size={23} color={c.foreground}/></TouchableOpacity></View><ScrollView contentContainerStyle={s.list}>{loading?<View style={s.state}><ActivityIndicator color={c.primary}/><Text style={s.muted}>Loading live alerts…</Text></View>:failed?<TouchableOpacity onPress={()=>void load()} style={s.state}><Feather name="wifi-off" size={22} color={c.mutedForeground}/><Text style={s.muted}>Live alerts are temporarily unavailable. Tap to retry.</Text></TouchableOpacity>:!items.length?<View style={s.state}><Feather name="inbox" size={25} color={c.mutedForeground}/><Text style={s.muted}>No live trade alerts yet.</Text></View>:items.map(item=>{const isUnread=!read.includes(item.id);return <Pressable key={item.id} onPress={()=>mark(item.id)} style={[s.card,isUnread&&s.unread]}><View style={s.top}><View style={s.icon}><Feather name="cpu" size={17} color={c.primary}/></View><Text style={s.cardTitle}>{item.title}</Text><Text style={s.time}>{relative(item.timestamp)}</Text></View><Text style={s.message}>{item.message}</Text><View style={s.bottom}><Text style={s.tag}>AI ALERT</Text><Text onPress={openSignalDesk} accessibilityRole="link" style={s.setup}>View Setup ›</Text></View></Pressable>})}</ScrollView></View>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:c.background,padding:20,paddingTop:58},header:{flexDirection:'row',justifyContent:'space-between'},title:{color:c.foreground,fontSize:25,fontFamily:'Inter_700Bold'},subtitle:{color:c.mutedForeground,fontSize:11,marginTop:4},list:{gap:11,paddingTop:22,paddingBottom:30},card:{backgroundColor:c.card,borderRadius:13,borderWidth:1,borderColor:c.border,padding:15,gap:11},unread:{borderLeftColor:c.primary,borderLeftWidth:3},top:{flexDirection:'row',alignItems:'center',gap:10},icon:{width:34,height:34,borderRadius:10,backgroundColor:`${c.primary}18`,alignItems:'center',justifyContent:'center'},cardTitle:{flex:1,color:c.foreground,fontFamily:'Inter_700Bold',fontSize:14},time:{color:c.mutedForeground,fontSize:10},message:{color:c.mutedForeground,fontSize:12,lineHeight:18},bottom:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},tag:{color:c.primary,borderColor:`${c.primary}55`,borderWidth:1,borderRadius:4,paddingHorizontal:6,paddingVertical:4,fontSize:9,fontFamily:'Inter_700Bold'},setup:{color:c.primary,fontSize:10,fontFamily:'Inter_700Bold'},state:{alignItems:'center',gap:10,paddingVertical:50},muted:{color:c.mutedForeground,fontSize:12,textAlign:'center'}});