import React, { useEffect, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { ActivityIndicator, Alert, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/utils/supabase';
import colors from '@/constants/colors';
const c = colors.light; const KEY = 'tradiqs.tradeJournal.notes.v1';
type ClosedTrade = { id: string; asset: string; side: 'BUY' | 'SELL'; pnl: number | null; created_at: string; closed_at: string | null };
export default function TradeJournalScreen() { const router = useRouter(); const insets = useSafeAreaInsets(); const { session } = useAuth(); const [notes, setNotes] = useState<Record<string, string>>({}); const [trades, setTrades] = useState<ClosedTrade[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { AsyncStorage.getItem(KEY).then((raw) => raw && setNotes(JSON.parse(raw))).catch(() => {}); }, []);
  useEffect(() => { let cancelled = false; (async () => { if (!session) { setLoading(false); return; } try { const { data, error: queryError } = await supabase.from('trades').select('id, asset, side, pnl, created_at, closed_at').eq('user_id', session.user.id).eq('status', 'CLOSED').order('closed_at', { ascending: false }); if (queryError) throw queryError; if (!cancelled) setTrades((data ?? []) as ClosedTrade[]); } catch (err) { if (!cancelled) setError(err instanceof Error ? err.message : 'Failed to load closed trades.'); } finally { if (!cancelled) setLoading(false); } })(); return () => { cancelled = true; }; }, [session]);
  const update = (id: string, value: string) => { const next = { ...notes, [id]: value }; setNotes(next); AsyncStorage.setItem(KEY, JSON.stringify(next)).catch(() => {}); };
  return <View style={[styles.container, { paddingTop: insets.top }]}><View style={styles.header}><View><Text style={styles.eyebrow}>EXECUTION REVIEW</Text><Text style={styles.title}>Trade Journal</Text></View><TouchableOpacity onPress={() => router.back()} accessibilityRole="button" accessibilityLabel="Close"><Feather name="x" size={23} color={c.foreground} /></TouchableOpacity></View>{loading ? <ActivityIndicator color={c.primary} style={styles.center} /> : !session ? <Text style={styles.empty}>Sign in to review your closed trades.</Text> : error ? <Text style={styles.error}>{error}</Text> : trades.length === 0 ? <Text style={styles.empty}>No closed trades yet. Your reflections will appear here after a trade.</Text> : <ScrollView contentContainerStyle={styles.list}>{trades.map((trade) => { const pnl = Number(trade.pnl ?? 0); return <View key={trade.id} style={styles.card}><View style={styles.row}><View><Text style={styles.asset}>{trade.asset}</Text><Text style={styles.meta}>{trade.side === 'BUY' ? 'LONG' : 'SHORT'} · {new Date(trade.closed_at ?? trade.created_at).toLocaleDateString()}</Text></View><Text style={[styles.pnl, { color: pnl >= 0 ? c.success : c.destructive }]}>{pnl >= 0 ? '+' : ''}${pnl.toFixed(2)}</Text></View><Text style={styles.outcome}>{pnl >= 0 ? 'WIN' : 'LOSS'}</Text><TextInput value={notes[trade.id] ?? ''} onChangeText={(value) => update(trade.id, value)} placeholder="What did you learn from this trade?" placeholderTextColor={c.mutedForeground} multiline style={styles.input} accessibilityLabel={`Note for ${trade.asset} trade`} /></View>; })}</ScrollView>}</View>; }
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: c.background, padding: 20, paddingTop: 58 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, eyebrow: { color: c.primary, fontSize: 10, letterSpacing: 1.4, fontFamily: 'Inter_700Bold' }, title: { color: c.foreground, fontSize: 24, fontFamily: 'Inter_700Bold', marginTop: 4 }, center: { marginTop: 40 }, empty: { color: c.mutedForeground, textAlign: 'center', marginTop: 48, lineHeight: 21 }, error: { color: c.destructive, textAlign: 'center', marginTop: 48, lineHeight: 21 }, list: { gap: 12, paddingVertical: 24 }, card: { backgroundColor: c.card, borderColor: c.border, borderWidth: 1, borderRadius: 14, padding: 16, gap: 10 }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, asset: { color: c.foreground, fontSize: 16, fontFamily: 'Inter_700Bold' }, meta: { color: c.mutedForeground, fontSize: 11, marginTop: 4 }, pnl: { fontSize: 17, fontFamily: 'Inter_700Bold' }, outcome: { color: c.mutedForeground, fontSize: 10, fontFamily: 'Inter_700Bold', letterSpacing: 1 }, input: { minHeight: 68, borderColor: c.border, borderWidth: 1, borderRadius: 9, padding: 10, color: c.foreground, fontSize: 13, textAlignVertical: 'top' } });