import React, { useState } from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { PaywallModal } from '@/components/PaywallModal';
import colors from '@/constants/colors';
const c = colors.light;
const PLANS = [['Pro', '$150 lifetime', 'Daily high-conviction signals'], ['Elite', '$500 lifetime', 'Signals plus private analysis'], ['Whale', '$5,000 lifetime', 'Institutional access and priority support']] as const;
export default function VipSignalsScreen() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const [paywall, setPaywall] = useState(false);
  return <View style={s.container}><ScrollView contentContainerStyle={[s.content, { paddingTop: Platform.OS === 'web' ? 20 : insets.top + 10 }]}><View style={s.header}><TouchableOpacity onPress={() => router.back()} accessibilityRole="button" accessibilityLabel="Go back"><Feather name="chevron-left" size={23} color={c.foreground} /></TouchableOpacity><Text style={s.title}>VIP Signals</Text><Feather name="star" size={21} color={c.secondary} /></View><View style={s.lock}><Feather name="lock" size={27} color={c.primary} /><Text style={s.lockTitle}>VIP Signals Channel</Text><Text style={s.body}>Private Telegram channel for traders who want early, high-conviction market intelligence and direct signal commentary.</Text><Text style={s.tag}>PRIVATE TELEGRAM CHANNEL</Text></View><Text style={s.section}>CHOOSE YOUR ACCESS</Text>{PLANS.map(([name, price, detail]) => <TouchableOpacity key={name} style={s.plan} onPress={() => setPaywall(true)} accessibilityRole="button" accessibilityLabel={`Unlock ${name} plan`}><View style={s.planIcon}><Feather name="zap" size={16} color={c.secondary} /></View><View style={s.planCopy}><Text style={s.planName}>{name}</Text><Text style={s.detail}>{detail}</Text></View><View><Text style={s.price}>{price}</Text><Feather name="chevron-right" size={18} color={c.secondary} /></View></TouchableOpacity>)}</ScrollView><PaywallModal visible={paywall} onClose={() => setPaywall(false)} /></View>;
}
import { Platform } from 'react-native';
const s = StyleSheet.create({ container: { flex: 1, backgroundColor: c.background }, content: { padding: 18, gap: 14 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, title: { color: c.foreground, fontSize: 22, fontFamily: 'Inter_700Bold' }, lock: { backgroundColor: c.card, borderWidth: 1, borderColor: c.primary, borderRadius: 16, padding: 22, gap: 12, marginTop: 14 }, lockTitle: { color: c.foreground, fontSize: 22, fontFamily: 'Inter_700Bold' }, body: { color: c.mutedForeground, lineHeight: 21, fontSize: 14 }, tag: { color: c.primary, fontSize: 10, fontFamily: 'Inter_700Bold', letterSpacing: 1.2 }, section: { color: c.mutedForeground, fontSize: 10, fontFamily: 'Inter_700Bold', letterSpacing: 1.2, marginTop: 8 }, plan: { backgroundColor: c.card, borderColor: c.border, borderWidth: 1, borderRadius: 13, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 11 }, planIcon: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#28183A', alignItems: 'center', justifyContent: 'center' }, planCopy: { flex: 1, gap: 3 }, planName: { color: c.foreground, fontSize: 16, fontFamily: 'Inter_700Bold' }, detail: { color: c.mutedForeground, fontSize: 11 }, price: { color: c.secondary, fontSize: 12, fontFamily: 'Inter_700Bold', marginBottom: 5 } });