import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Modal, Platform, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import * as WebBrowser from 'expo-web-browser';
import { Feather } from '@expo/vector-icons';
import { customFetch } from '@workspace/api-client-react';
import colors from '@/constants/colors';
const c = colors.light;
type Category = 'all'|'crypto'|'forex'|'stocks';
type Article = { id:string; title:string; summary:string; source:string; url:string; category:string; timestamp:number; imageUrl:string };
const categories: Array<[Category,string]>=[['all','All'],['crypto','Crypto'],['forex','Forex'],['stocks','Stocks']];
const ago=(timestamp:number)=>{const minutes=Math.max(1,Math.floor((Date.now()-timestamp)/60000)); return minutes<60?`${minutes}m ago`:minutes<1440?`${Math.floor(minutes/60)}h ago`:`${Math.floor(minutes/1440)}d ago`;};
export function LatestInsightsModal({ visible, onClose }: { visible:boolean; onClose:()=>void }) {
  const [category,setCategory]=useState<Category>('all'); const [articles,setArticles]=useState<Article[]>([]); const [loading,setLoading]=useState(false);
  useEffect(()=>{if(!visible)return; setLoading(true); customFetch<Article[]>(`/api/market-news?category=${category}`).then(x=>setArticles(Array.isArray(x)?x:[])).catch(()=>setArticles([])).finally(()=>setLoading(false));},[visible,category]);
  const open=async(url:string)=>{if(Platform.OS==='web'){globalThis.open(url,'_blank');return;} await WebBrowser.openBrowserAsync(url);};
  return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><View style={s.page}><View style={s.header}><TouchableOpacity onPress={onClose}><Feather name="x" size={23} color={c.foreground}/></TouchableOpacity><Text style={s.title}>Latest Insights</Text><Feather name="book-open" size={20} color={c.primary}/></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{categories.map(([key,label])=><TouchableOpacity key={key} onPress={()=>setCategory(key)} style={[s.pill,category===key&&s.pillOn]}><Text style={[s.pillText,category===key&&s.pillTextOn]}>{label}</Text></TouchableOpacity>)}</ScrollView><ScrollView contentContainerStyle={s.content}>{loading?<View style={s.center}><ActivityIndicator color={c.primary}/><Text style={s.muted}>Loading live insights…</Text></View>:articles.length?articles.map(a=><TouchableOpacity key={a.id} style={s.article} onPress={()=>void open(a.url)}><View style={s.top}><Text style={s.category}>{a.source}</Text><Text style={s.time}>{ago(a.timestamp)}</Text></View><Text style={s.headline}>{a.title}</Text><Text numberOfLines={3} style={s.summary}>{a.summary}</Text><Text style={s.read}>READ ARTICLE ↗</Text></TouchableOpacity>):<View style={s.center}><Text style={s.muted}>No insights are available for this category right now.</Text></View>}</ScrollView></View></Modal>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:c.background},header:{padding:18,paddingTop:24,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:c.border},title:{color:c.foreground,fontSize:20,fontFamily:'Inter_700Bold'},filters:{padding:14,gap:8},pill:{paddingHorizontal:15,paddingVertical:8,borderRadius:18,backgroundColor:c.card,borderWidth:1,borderColor:c.border},pillOn:{backgroundColor:c.primary,borderColor:c.primary},pillText:{color:c.mutedForeground,fontFamily:'Inter_700Bold',fontSize:11},pillTextOn:{color:c.primaryForeground},content:{padding:18,gap:14,paddingBottom:38},article:{backgroundColor:c.card,borderColor:c.border,borderWidth:1,borderRadius:14,padding:16,gap:10},top:{flexDirection:'row',justifyContent:'space-between'},category:{color:c.primary,fontSize:10,fontFamily:'Inter_700Bold'},time:{color:c.mutedForeground,fontSize:10},headline:{color:c.foreground,fontSize:16,lineHeight:22,fontFamily:'Inter_700Bold'},summary:{color:c.mutedForeground,fontSize:13,lineHeight:19},read:{color:c.primary,fontSize:10,fontFamily:'Inter_700Bold',letterSpacing:.7},center:{alignItems:'center',gap:12,paddingVertical:42},muted:{color:c.mutedForeground,textAlign:'center'}});