import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Modal, Platform, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import * as WebBrowser from 'expo-web-browser';
import { Feather } from '@expo/vector-icons';
import { customFetch } from '@workspace/api-client-react';
import colors from '@/constants/colors';
const c = colors.light;
type Category = 'all'|'crypto'|'forex'|'stocks';
type Article = { id:string; title:string; summary:string; source:string; url:string; category:string; timestamp:number; imageUrl:string };
const categories: Array<[Category,string]>=[['all','All'],['crypto','Crypto'],['forex','Forex'],['stocks','Stocks']];
const formatRelativeTime=(timestamp:number)=>{if(!timestamp||Number.isNaN(timestamp))return 'Just now';const ms=timestamp<1e11?timestamp*1000:timestamp;const diffHours=Math.floor((Date.now()-ms)/(1000*60*60));if(diffHours<1)return 'Just now';if(diffHours<24)return `${diffHours}h ago`;return `${Math.floor(diffHours/24)}d ago`;};
export function LatestInsightsModal({ visible, onClose }: { visible:boolean; onClose:()=>void }) {
  const [category,setCategory]=useState<Category>('all'); const [articles,setArticles]=useState<Article[]>([]); const [loading,setLoading]=useState(false); const [selected,setSelected]=useState<Article|null>(null);
  useEffect(()=>{if(!visible)return; setLoading(true); customFetch<Article[]>(`/api/market-news?category=${category}`).then(x=>setArticles(Array.isArray(x)?x:[])).catch(()=>setArticles([])).finally(()=>setLoading(false));},[visible,category]);
  const openInAppBrowser=async(url:string)=>{if(Platform.OS==='web'){globalThis.open(url,'_blank');return;}await WebBrowser.openBrowserAsync(url,{presentationStyle:WebBrowser.WebBrowserPresentationStyle.PAGE_SHEET,controlsColor:'#00E676',dismissButtonStyle:'close'});};
  return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><View style={s.page}><View style={s.header}><TouchableOpacity onPress={onClose}><Feather name="x" size={23} color={c.foreground}/></TouchableOpacity><Text style={s.title}>Latest Insights</Text><Feather name="book-open" size={20} color={c.primary}/></View>{selected?<ScrollView contentContainerStyle={s.content}><View style={s.readerTop}><TouchableOpacity onPress={()=>setSelected(null)}><Text style={s.back}>‹ BACK TO INSIGHTS</Text></TouchableOpacity><TouchableOpacity style={s.original} onPress={()=>void openInAppBrowser(selected.url)}><Text style={s.originalText}>OPEN ORIGINAL SOURCE ↗</Text></TouchableOpacity></View><Text style={s.category}>{selected.source} · {formatRelativeTime(selected.timestamp)}</Text><Text style={s.readerTitle}>{selected.title}</Text><Text style={s.readerBody}>{selected.summary}</Text></ScrollView>:<><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{categories.map(([key,label])=><TouchableOpacity key={key} onPress={()=>setCategory(key)} style={[s.pill,category===key&&s.pillOn]}><Text style={[s.pillText,category===key&&s.pillTextOn]}>{label}</Text></TouchableOpacity>)}</ScrollView><ScrollView contentContainerStyle={s.content}>{loading?<View style={s.center}><ActivityIndicator color={c.primary}/><Text style={s.muted}>Loading live insights…</Text></View>:articles.length?articles.map(a=><TouchableOpacity key={a.id} style={s.article} onPress={()=>setSelected(a)}><View style={s.top}><Text style={s.category}>{a.source}</Text><Text style={s.time}>{formatRelativeTime(a.timestamp)}</Text></View><Text style={s.headline}>{a.title}</Text><Text numberOfLines={3} style={s.summary}>{a.summary}</Text><Text style={s.read}>READ ARTICLE →</Text></TouchableOpacity>):<View style={s.center}><Text style={s.muted}>No insights are available for this category right now.</Text></View>}</ScrollView></>}</View></Modal>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:c.background},header:{padding:18,paddingTop:24,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:c.border},title:{color:c.foreground,fontSize:20,fontFamily:'Inter_700Bold'},filters:{padding:14,gap:8},pill:{paddingHorizontal:15,paddingVertical:8,borderRadius:18,backgroundColor:c.card,borderWidth:1,borderColor:c.border},pillOn:{backgroundColor:c.primary,borderColor:c.primary},pillText:{color:c.mutedForeground,fontFamily:'Inter_700Bold',fontSize:11},pillTextOn:{color:c.primaryForeground},content:{padding:18,gap:14,paddingBottom:38},article:{backgroundColor:c.card,borderColor:c.border,borderWidth:1,borderRadius:14,padding:16,gap:10},top:{flexDirection:'row',justifyContent:'space-between'},category:{color:c.primary,fontSize:10,fontFamily:'Inter_700Bold'},time:{color:c.mutedForeground,fontSize:10},headline:{color:c.foreground,fontSize:16,lineHeight:22,fontFamily:'Inter_700Bold'},summary:{color:c.mutedForeground,fontSize:13,lineHeight:19},read:{color:c.primary,fontSize:10,fontFamily:'Inter_700Bold',letterSpacing:.7},center:{alignItems:'center',gap:12,paddingVertical:42},muted:{color:c.mutedForeground,textAlign:'center'},back:{color:c.primary,fontSize:11,fontFamily:'Inter_700Bold'},readerTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},readerTitle:{color:c.foreground,fontSize:25,lineHeight:32,fontFamily:'Inter_700Bold'},readerBody:{color:c.mutedForeground,fontSize:16,lineHeight:25},original:{borderWidth:1,borderColor:c.primary,borderRadius:8,padding:9,alignItems:'center'},originalText:{color:c.primary,fontSize:9,fontFamily:'Inter_700Bold'}});