import Link from 'next/link';
import { ArrowRight, Download, Radio, ShieldCheck, Sparkles } from 'lucide-react';
import { Faqs, SectionTitle, toolCards } from './components/site';

export default function Home() {
  return <main className="grid-lines">
    <section className="mx-auto grid max-w-7xl gap-14 px-5 pb-20 pt-20 lg:grid-cols-[1.1fr_.9fr] lg:px-8 lg:pb-32 lg:pt-28">
      <div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-cyan/30 bg-cyan/10 px-3 py-2 text-xs font-bold text-cyan"><span className="h-2 w-2 animate-pulse rounded-full bg-cyan" /> MARKET INTELLIGENCE, REIMAGINED</div><h1 className="max-w-3xl text-5xl font-black leading-[.98] tracking-[-.06em] md:text-7xl">The Institutional Edge <span className="text-cyan">in Your Pocket.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted">Trade with the clarity of a desk, the discipline of a system, and the intelligence of an always-on analyst.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/contact" className="flex items-center gap-3 rounded-xl bg-cyan px-5 py-3 font-bold text-ink"><Download className="h-5 w-5" /> Download the app <ArrowRight className="h-4 w-4" /></Link><Link href="/about" className="rounded-xl border border-white/15 px-5 py-3 font-semibold hover:border-cyan">See how it works</Link></div><div className="mt-8 flex gap-6 text-xs text-muted"><span>iOS App Store</span><span>Google Play</span><span className="text-cyan">Free to start</span></div></div>
      <div className="glass glow relative overflow-hidden rounded-[2rem] p-5 lg:p-7"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-cyan/10 blur-3xl" /><div className="relative rounded-2xl border border-white/10 bg-ink/80 p-5"><div className="flex justify-between text-xs text-muted"><span>BTC / USDT</span><span className="text-green-400">+4.82%</span></div><div className="mt-8 flex h-48 items-end gap-2">{[35,55,42,72,60,80,66,92,76,100,88,112,96].map((h, i) => <span key={i} style={{ height: `${h}%` }} className="flex-1 rounded-t bg-gradient-to-t from-cyan/20 to-cyan" />)}</div><div className="mt-5 flex items-center justify-between border-t border-white/10 pt-4"><div><p className="text-[10px] uppercase tracking-widest text-muted">AI conviction</p><p className="mt-1 text-2xl font-bold text-cyan">92.4%</p></div><span className="rounded-lg bg-green-400/10 px-3 py-2 text-xs font-bold text-green-400">BUY SIGNAL</span></div></div></div>
    </section>
    <div className="overflow-hidden border-y border-white/10 bg-card/70 py-3"><div className="ticker-track flex gap-10 text-xs font-bold text-muted">{['EURUSD 1.0842 +0.42%', 'BTCUSDT 67,420 +4.82%', 'XAUUSD 2,348 -0.18%', 'AAPL 192.44 +1.20%', 'GBPUSD 1.2710 +0.31%', 'EURUSD 1.0842 +0.42%', 'BTCUSDT 67,420 +4.82%', 'XAUUSD 2,348 -0.18%'].map((x, i) => <span key={i}>{x}</span>)}</div></div>
    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><SectionTitle eyebrow="The edge" title="Everything serious traders need, without the noise." copy="One focused terminal for signal discovery, execution discipline, and measurable growth." /><div className="grid gap-4 md:grid-cols-3">{toolCards.map(({ icon: Icon, title, copy }) => <div key={title} className="glass rounded-3xl p-7"><Icon className="mb-12 h-8 w-8 text-cyan" /><h3 className="text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted">{copy}</p></div>)}</div></section>
    <section className="mx-auto grid max-w-7xl gap-12 px-5 pb-24 lg:grid-cols-2 lg:px-8"><div><SectionTitle eyebrow="Built for conviction" title="A calmer way to meet the market." copy="TradiQs AI turns complex market context into a repeatable process you can actually follow." /><div className="grid gap-4 text-sm text-muted"><div className="flex gap-3"><Sparkles className="h-5 w-5 shrink-0 text-cyan" /><span>AI explanations that show the why behind every signal.</span></div><div className="flex gap-3"><ShieldCheck className="h-5 w-5 shrink-0 text-cyan" /><span>Risk-first tools that keep your downside visible.</span></div><div className="flex gap-3"><Radio className="h-5 w-5 shrink-0 text-cyan" /><span>Live market awareness across forex, crypto, and stocks.</span></div></div></div><Faqs /></section>
  </main>;
}