import Link from 'next/link';
import { ArrowUpRight, Bot, FilePlus2, Radio, UserPlus, Users, WalletCards } from 'lucide-react';
import { getSupabaseServer } from '../../../lib/supabase-server';
export const dynamic = 'force-dynamic';
export default async function AdminDashboard() {
  let users = 0, affiliates = 0, subscribers = 0, signals = 0, waitlist = 0;
  try {
    const supabase = getSupabaseServer();
    if (supabase) {
      const [u, a, p, s, w] = await Promise.all([supabase.from('profiles').select('*', { count: 'exact', head: true }), supabase.from('affiliates').select('*', { count: 'exact', head: true }), supabase.from('profiles').select('*', { count: 'exact', head: true }).in('tier', ['pro', 'elite', 'whale', 'vip']), supabase.from('ai_signals').select('*', { count: 'exact', head: true }), supabase.from('waitlist').select('*', { count: 'exact', head: true })]);
      users = u.count ?? 0; affiliates = a.count ?? 0; subscribers = p.count ?? 0; signals = s.count ?? 0; waitlist = w.count ?? 0;
    }
  } catch {}
  const metrics = [['Total Users', users, Users], ['Premium Subscribers', subscribers, WalletCards], ['Active Signals', signals, Radio], ['Waitlist Signups', waitlist, UserPlus], ['Total Affiliates', affiliates, Bot]] as const;
  return <div className="p-5 md:p-8 lg:p-10"><div className="mb-10"><p className="text-xs font-bold uppercase tracking-[.25em] text-cyan">Command center</p><h1 className="mt-3 text-3xl font-black">Good morning, Admin.</h1><p className="mt-2 text-sm text-muted">Live metrics from your shared Supabase workspace.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{metrics.map(([label, value, Icon]) => <div className="rounded-2xl border border-white/10 bg-card p-5" key={label}><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-cyan/10 text-cyan"><Icon className="h-4 w-4" /></span><p className="mt-7 text-xs uppercase tracking-widest text-muted">{label}</p><p className="mt-2 text-3xl font-bold">{value.toLocaleString()}</p></div>)}</div><div className="mt-6 rounded-2xl border border-white/10 bg-card p-6"><h2 className="font-bold">Quick Actions</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Link href="/admin/blog" className="flex items-center gap-3 rounded-xl border border-white/10 p-4 text-sm hover:border-cyan"><FilePlus2 className="h-4 w-4 text-cyan" /> Write a new post</Link><Link href="/admin/signals" className="flex items-center gap-3 rounded-xl border border-white/10 p-4 text-sm hover:border-cyan"><Radio className="h-4 w-4 text-cyan" /> Broadcast a signal</Link><Link href="/admin/users" className="flex items-center gap-3 rounded-xl border border-white/10 p-4 text-sm hover:border-cyan"><Users className="h-4 w-4 text-cyan" /> Manage users <ArrowUpRight className="h-3 w-3" /></Link><Link href="/admin/waitlist" className="flex items-center gap-3 rounded-xl border border-white/10 p-4 text-sm hover:border-cyan"><UserPlus className="h-4 w-4 text-cyan" /> View waitlist <ArrowUpRight className="h-3 w-3" /></Link></div></div></div>;
}