-- Cache one-line Anthropic strategy briefs in Supabase. The cache is strictly
-- server-owned: clients never query or write it, because it is operational
-- data and exposing it would invite cache poisoning and prompt-cost abuse.
--
-- The API looks up a matching bot/allocation written in the previous 15
-- minutes. Keeping allocation in the cache key prevents an old 10% brief
-- from being presented as analysis for a 100% allocation.
--
-- Safe to run more than once.

create table if not exists public.autopilot_strategy_brief_cache (
  id bigint generated by default as identity primary key,
  bot_name text not null,
  capital_percent numeric not null check (capital_percent between 10 and 100),
  brief text not null check (length(trim(brief)) > 0),
  created_at timestamptz not null default now()
);

create index if not exists autopilot_strategy_brief_cache_lookup_idx
  on public.autopilot_strategy_brief_cache (
    bot_name,
    capital_percent,
    created_at desc
  );

alter table public.autopilot_strategy_brief_cache enable row level security;

-- Explicitly deny app roles. The Supabase service role bypasses RLS and is
-- the only identity the API server uses to operate this cache.
revoke all on public.autopilot_strategy_brief_cache from anon, authenticated;
revoke all on sequence public.autopilot_strategy_brief_cache_id_seq
  from anon, authenticated;

-- A read-only schema probe for the API's startup/mobile readiness check.
-- Calling set_active_bot with a null strategy would deactivate a real bot, so
-- the health check must inspect its presence rather than invoking it.
create or replace function public.autopilot_dependencies_ready()
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select jsonb_build_object(
    'set_active_bot',
      to_regprocedure('public.set_active_bot(text,numeric)') is not null,
    'autopilot_strategies',
      to_regclass('public.autopilot_strategies') is not null,
    'profile_bot_columns',
      exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'profiles'
          and column_name = 'active_bot'
      ) and exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'profiles'
          and column_name = 'allocated_capital'
      )
  );
$$;

revoke all on function public.autopilot_dependencies_ready() from public, anon, authenticated;