-- Server-curated financial news for the in-app Notifications reader.
-- Safe to run more than once.
--
-- External providers and Anthropic are called only by the API server. Clients
-- can read the published cache but cannot create, edit, or poison stories.

create table if not exists public.market_news (
  id bigint generated by default as identity primary key,
  external_id text not null unique,
  headline text not null check (length(trim(headline)) > 0),
  ai_summary text not null check (length(trim(ai_summary)) > 0),
  category text not null check (category in ('crypto', 'forex', 'stocks')),
  sentiment text not null check (sentiment in ('Bullish', 'Bearish', 'Neutral')),
  url text not null check (url ~* '^https?://'),
  published_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists market_news_published_at_idx
  on public.market_news (published_at desc);

alter table public.market_news enable row level security;

revoke all on public.market_news from anon, authenticated;
revoke all on sequence public.market_news_id_seq from anon, authenticated;

drop policy if exists "market_news_readable" on public.market_news;
create policy "market_news_readable"
  on public.market_news for select
  to authenticated
  using (true);

grant select on public.market_news to authenticated;