import Link from 'next/link';
import { FileText, FolderOpen, HelpCircle, LayoutDashboard, MessageSquareMore, Settings, ShieldCheck, UserPlus } from 'lucide-react';
import { AdminHeader } from './admin-header';
import { LogoutButton } from './logout-button';
import { SessionWarningBanner } from './session-warning';
const nav = [['Dashboard', '/admin', LayoutDashboard], ['Market Insights', '/admin/blog', FileText], ['Categories & Tags', '/admin/categories', FolderOpen], ['Waitlist Leads', '/admin/waitlist', UserPlus], ['Help Desk', '/admin/inbox', HelpCircle], ['Comments Moderation', '/admin/comments', MessageSquareMore], ['System Settings', '/admin/settings', Settings]] as const;
export default function AdminLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return <div className="min-h-screen bg-[#050505] text-white"><aside className="fixed inset-y-0 left-0 hidden w-64 border-r border-gray-800 bg-[#0D0D0D] p-5 lg:block"><Link href="/admin" className="mb-10 flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#00FFFF] text-xs font-black text-black">TQ</span><span className="font-bold">TradiQs <span className="text-[#00FFFF]">CMS</span></span></Link><nav className="grid gap-1">{nav.map(([label, href, Icon]) => <Link key={label} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm ${label === 'Dashboard' ? 'bg-[#00FFFF]/10 text-[#00FFFF]' : 'text-gray-400 hover:bg-white/5 hover:text-white'}`}><Icon className="h-4 w-4" />{label}</Link>)}<LogoutButton /></nav><div className="absolute bottom-6 left-5 right-5 rounded-2xl border border-[#00FFFF]/20 bg-[#00FFFF]/5 p-4"><p className="flex items-center gap-2 text-xs font-bold text-[#00FFFF]"><ShieldCheck className="h-3.5 w-3.5" /> SYSTEM STATUS</p><p className="mt-2 flex items-center gap-2 text-xs text-gray-400"><span className="h-2 w-2 rounded-full bg-green-400" /> All systems operational</p></div></aside><div className="min-h-screen lg:ml-64"><AdminHeader /><main>{children}</main></div><SessionWarningBanner /></div>;
}
