import React, { useEffect, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { ActivityIndicator, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { Stack } from 'expo-router';

const CYAN = '#00F0FF';
const BROKERS = ['Binance', 'Bybit', 'Exness', 'Oanda'] as const;
type Broker = typeof BROKERS[number];
const keyFor = (broker: Broker) => `tradiqs.broker-sync.${broker.toLowerCase()}`;
export default function BrokerSyncScreen() {
  const [selected, setSelected] = useState<Broker | null>(null); const [apiKey, setApiKey] = useState(''); const [secret, setSecret] = useState(''); const [connecting, setConnecting] = useState(false); const [connected, setConnected] = useState(false); const [mirror, setMirror] = useState(false);
  useEffect(() => { if (!selected) return; setConnected(false); setApiKey(''); setSecret(''); AsyncStorage.getItem(keyFor(selected)).then((raw) => { if (!raw) return; try { const data = JSON.parse(raw) as { apiKey?: string; secret?: string; mirror?: boolean }; setApiKey(data.apiKey ?? ''); setSecret(data.secret ?? ''); setMirror(Boolean(data.mirror)); setConnected(Boolean(data.apiKey && data.secret)); } catch { /* use blank form */ } }).catch(() => {}); }, [selected]);
  const connect = () => { if (!selected || !apiKey.trim() || !secret.trim()) return; setConnecting(true); setTimeout(() => { AsyncStorage.setItem(keyFor(selected), JSON.stringify({ apiKey: apiKey.trim(), secret: secret.trim(), mirror })).then(() => setConnected(true)).finally(() => setConnecting(false)); }, 2000); };
  const toggleMirror = (value: boolean) => { setMirror(value); if (selected) AsyncStorage.setItem(keyFor(selected), JSON.stringify({ apiKey, secret, mirror: value })).catch(() => {}); };
  return <View style={styles.container}><Stack.Screen options={{ title: 'Exchange Integration', headerStyle: { backgroundColor: '#0A0B0E' }, headerTintColor: '#FFF' }} /><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.eyebrow}>BROKERSYNC</Text><Text style={styles.title}>Exchange Integration</Text><Text style={styles.intro}>Connect an exchange locally and choose whether AI signals may mirror to your live account.</Text><Text style={styles.section}>SELECT YOUR BROKER</Text><View style={styles.grid}>{BROKERS.map((broker) => <TouchableOpacity key={broker} style={[styles.broker, selected === broker && styles.selected]} onPress={() => setSelected(broker)}><Feather name="bar-chart-2" size={22} color={selected === broker ? CYAN : '#858D98'} /><Text style={[styles.brokerName, selected === broker && styles.selectedText]}>{broker}</Text></TouchableOpacity>)}</View>{selected && !connected && <View style={styles.form}><Text style={styles.formTitle}>{selected} API credentials</Text><Text style={styles.caption}>Stored locally on this device.</Text><TextInput value={apiKey} onChangeText={setApiKey} placeholder="API Key" placeholderTextColor="#737983" autoCapitalize="none" style={styles.input} /><TextInput value={secret} onChangeText={setSecret} placeholder="Secret Key" placeholderTextColor="#737983" secureTextEntry autoCapitalize="none" style={styles.input} /><TouchableOpacity style={[styles.connect, (!apiKey || !secret) && styles.disabled]} disabled={!apiKey || !secret || connecting} onPress={connect}>{connecting ? <ActivityIndicator color="#071014" /> : <Text style={styles.connectText}>CONNECT SECURELY</Text>}</TouchableOpacity></View>}{selected && connected && <View style={styles.connected}><Text style={styles.status}>🟢 Status: Connected</Text><Text style={styles.connectedCopy}>{selected} integration is active on this device.</Text><View style={styles.mirrorRow}><View><Text style={styles.mirrorTitle}>Mirror AI Signals to Live Account</Text><Text style={styles.caption}>Require your exchange connection for execution.</Text></View><Switch value={mirror} onValueChange={toggleMirror} trackColor={{ false: '#303641', true: '#1A6670' }} thumbColor={mirror ? CYAN : '#9BA1AA'} /></View></View>}</ScrollView></View>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#0A0B0E' }, content: { padding: 20, paddingBottom: 44 }, eyebrow: { color: CYAN, fontSize: 10, fontWeight: '800', letterSpacing: 1.8 }, title: { color: '#FFF', fontSize: 27, fontWeight: '800', marginTop: 8 }, intro: { color: '#89909B', fontSize: 13, lineHeight: 19, marginTop: 8 }, section: { color: '#6D727B', fontSize: 10, fontWeight: '800', letterSpacing: 1.5, marginTop: 27, marginBottom: 10 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, broker: { width: '48%', minHeight: 90, justifyContent: 'center', alignItems: 'center', gap: 9, backgroundColor: '#16181D', borderWidth: 1, borderColor: '#292D35', borderRadius: 12 }, selected: { borderColor: CYAN, backgroundColor: '#101E23' }, brokerName: { color: '#D5D8DE', fontSize: 13, fontWeight: '800' }, selectedText: { color: CYAN }, form: { backgroundColor: '#16181D', borderWidth: 1, borderColor: '#292D35', borderRadius: 14, padding: 16, marginTop: 20 }, formTitle: { color: '#FFF', fontSize: 16, fontWeight: '800' }, caption: { color: '#7C8490', fontSize: 11, marginTop: 5 }, input: { color: '#FFF', backgroundColor: '#0C0E12', borderColor: '#303641', borderWidth: 1, borderRadius: 9, padding: 13, marginTop: 12 }, connect: { backgroundColor: CYAN, borderRadius: 10, padding: 15, alignItems: 'center', marginTop: 14 }, disabled: { opacity: .45 }, connectText: { color: '#071014', fontWeight: '900', letterSpacing: .8 }, connected: { backgroundColor: '#102019', borderWidth: 1, borderColor: '#2ECA8B', borderRadius: 14, padding: 16, marginTop: 20 }, status: { color: '#7CFFB7', fontSize: 16, fontWeight: '900' }, connectedCopy: { color: '#B1C6B9', fontSize: 12, marginTop: 7 }, mirrorRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, borderTopWidth: 1, borderTopColor: '#294636', paddingTop: 15, marginTop: 15 }, mirrorTitle: { color: '#FFF', fontSize: 13, fontWeight: '700', maxWidth: 230 } });