import Link from 'next/link';
import { ArrowUpRight, BarChart3, Bot, BrainCircuit, ChevronDown, Globe, Video } from 'lucide-react';

export function Navbar() {
  return <header className="sticky top-0 z-50 border-b border-white/10 bg-ink/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Link href="/" className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-cyan text-sm font-black text-ink">TQ</span><span className="text-lg font-bold tracking-tight">TradiQs<span className="text-cyan">AI</span></span></Link><nav className="hidden items-center gap-7 text-sm text-muted md:flex"><Link href="/about" className="hover:text-white">About</Link><Link href="/blog" className="hover:text-white">Insights</Link><Link href="/contact" className="hover:text-white">Contact</Link><Link href="/admin" className="hover:text-white">CMS</Link></nav><Link href="/contact" className="rounded-full bg-cyan px-4 py-2 text-xs font-bold text-ink hover:bg-white">Get early access <ArrowUpRight className="ml-1 inline h-3 w-3" /></Link></div></header>;
}
export function Footer() {
  return <footer className="border-t border-white/10 px-5 py-14 lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-4"><div className="md:col-span-2"><div className="mb-4 flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-cyan text-xs font-black text-ink">TQ</span><b>TradiQsAI</b></div><p className="max-w-sm text-sm leading-6 text-muted">Institutional-grade market intelligence, built for traders who refuse to guess.</p></div><div><p className="mb-4 text-xs font-bold uppercase tracking-widest text-cyan">Explore</p><div className="grid gap-3 text-sm text-muted"><Link href="/about">About</Link><Link href="/blog">Market insights</Link><Link href="/contact">Contact</Link></div></div><div><p className="mb-4 text-xs font-bold uppercase tracking-widest text-cyan">Legal</p><div className="grid gap-3 text-sm text-muted"><Link href="/privacy">Privacy Policy</Link><Link href="/terms">Terms of Service</Link><span>support@trediqsAI.com</span></div></div></div><div className="mx-auto mt-12 flex max-w-7xl justify-between border-t border-white/10 pt-6 text-xs text-muted"><span>© 2026 TradiQs AI</span><span className="flex gap-4"><Globe className="h-4 w-4" /><Video className="h-4 w-4" /></span></div></footer>;
}
export function SectionTitle({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <div className="mb-10 max-w-2xl"><p className="mb-3 text-xs font-bold uppercase tracking-[.25em] text-cyan">{eyebrow}</p><h2 className="text-3xl font-bold tracking-tight md:text-5xl">{title}</h2><p className="mt-4 leading-7 text-muted">{copy}</p></div>; }
export const toolCards = [{ icon: BrainCircuit, title: 'AI Signal Generator', copy: 'Turn a chart into a high-conviction BUY or SELL thesis with clear entries, targets, and invalidation.' }, { icon: Bot, title: 'AutoPilot Bots', copy: 'Deploy disciplined GRID and DCA strategies that keep working while you focus on the bigger picture.' }, { icon: BarChart3, title: 'Risk Management', copy: 'Size every position with institutional discipline. Know your downside before the market moves.' }];
export function Faqs() { const faqs = ['How accurate are the AI Signals?', 'What brokers do you support?', 'Is TradiQs AI suitable for beginners?', 'Does AutoPilot trade with real money?']; return <div className="grid gap-3">{faqs.map((q) => <details key={q} className="glass group rounded-2xl p-5"><summary className="flex cursor-pointer list-none items-center justify-between font-semibold">{q}<ChevronDown className="h-4 w-4 text-cyan transition group-open:rotate-180" /></summary><p className="mt-3 text-sm leading-6 text-muted">TradiQs AI combines market structure, momentum, liquidity, and risk context into a transparent simulated trading workflow. Always validate ideas and manage your own risk.</p></details>)}</div>; }