import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { customFetch } from '@workspace/api-client-react';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/utils/supabase';
import { useRouter } from 'expo-router';

type Signal = { id: string; asset: string; direction: 'BUY' | 'SELL'; entry: number; take_profit: number; stop_loss: number; status: 'pending' | 'active' | 'won' | 'lost'; is_premium: boolean; created_at: string };
type Filter = 'All' | 'Free' | 'Premium' | 'Active' | 'Pending';
const filters: Filter[] = ['All', 'Free', 'Premium', 'Active', 'Pending'];
export const LOCKED_RATIONALE_TEASER = 'AI rationale locked — upgrade to Pro to see why this trade was called.';
const initial = { asset: '', direction: 'BUY' as 'BUY' | 'SELL', entry: '', takeProfit: '', stopLoss: '', status: 'active' as Signal['status'], isPremium: true };

export default function SignalsScreen() {
  const { session } = useAuth(); const router = useRouter();
  const [signals, setSignals] = useState<Signal[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [filter, setFilter] = useState<Filter>('All'); const [role, setRole] = useState('user'); const [plan, setPlan] = useState('free');
  const [publishOpen, setPublishOpen] = useState(false); const [form, setForm] = useState(initial); const [publishing, setPublishing] = useState(false);
  const premium = role === 'admin' || plan === 'pro' || plan === 'elite';
  const load = useCallback(async () => { setLoading(true); setError(''); try { const data = await customFetch<unknown>('/api/signals/broadcast'); setSignals(Array.isArray(data) ? data as Signal[] : []); if (!Array.isArray(data)) setError('Failed to load signals.'); } catch { setSignals([]); setError('Failed to load signals.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (!session?.user.id) return; void supabase.from('profiles').select('role,tier').eq('id', session.user.id).maybeSingle().then(({ data }) => { setRole(data?.role?.toLowerCase() ?? 'user'); setPlan(data?.tier?.toLowerCase() ?? 'free'); }); }, [session?.user.id]);
  const visible = useMemo(() => signals.filter(s => filter === 'All' || filter === 'Free' ? !s.is_premium : filter === 'Premium' ? s.is_premium : s.status === filter.toLowerCase()), [filter, signals]);
  const publish = async () => { const entry = Number(form.entry), takeProfit = Number(form.takeProfit), stopLoss = Number(form.stopLoss); if (!form.asset.trim() || !entry || !takeProfit || !stopLoss) return; setPublishing(true); try { await customFetch('/api/signals/broadcast', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ asset: form.asset.trim().toUpperCase(), direction: form.direction, entry, takeProfit, stopLoss, status: form.status, isPremium: form.isPremium }) }); setPublishOpen(false); setForm(initial); await load(); } catch { setError('Unable to publish signal.'); } finally { setPublishing(false); } };
  return <View style={styles.page}><View style={styles.header}><View><Text style={styles.eyebrow}>LIVE TRADE IDEAS</Text><Text style={styles.title}>Signal Desk</Text></View>{role === 'admin' && <TouchableOpacity style={styles.add} onPress={() => setPublishOpen(true)}><Feather name="plus" size={24} color="#071014" /></TouchableOpacity>}</View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{filters.map(f => <Pressable key={f} onPress={() => setFilter(f)} style={[styles.chip, filter === f && styles.chipOn]}><Text style={[styles.chipText, filter === f && styles.chipTextOn]}>{f}</Text></Pressable>)}</ScrollView>{loading ? <View style={styles.center}><ActivityIndicator color="#00F0FF" /><Text style={styles.muted}>Loading live signals…</Text></View> : <ScrollView contentContainerStyle={styles.list}>{error ? <TouchableOpacity onPress={load}><Text style={styles.error}>{error} Tap to retry.</Text></TouchableOpacity> : null}{visible.map(s => <SignalCard key={s.id} signal={s} locked={s.is_premium && !premium} onUpgrade={() => router.push('/paywall' as never)} />)}{!error && !visible.length ? <Text style={styles.muted}>No signals match this filter.</Text> : null}</ScrollView>}<PublishModal visible={publishOpen} form={form} setForm={setForm} close={() => setPublishOpen(false)} submit={publish} saving={publishing} /></View>;
}
function SignalCard({ signal, locked, onUpgrade }: { signal: Signal; locked: boolean; onUpgrade: () => void }) { const buy = signal.direction === 'BUY'; return <View style={styles.card}><View style={styles.cardTop}><View><Text style={styles.asset}>{signal.asset}</Text><Text style={[styles.direction, { color: buy ? '#28D68A' : '#FF6576' }]}>{signal.direction}</Text></View><View><Text style={styles.status}>{signal.status.toUpperCase()}</Text><Text style={styles.badge}>{signal.is_premium ? 'PREMIUM' : 'FREE'}</Text></View></View><View style={[styles.levels, locked && styles.blur]}>{[['ENTRY', signal.entry], ['TP', signal.take_profit], ['SL', signal.stop_loss]].map(([label, value]) => <View key={String(label)}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>)}</View>{locked ? <TouchableOpacity style={styles.unlock} onPress={onUpgrade}><Feather name="lock" size={14} color="#071014" /><Text style={styles.unlockText}>UPGRADE TO PRO TO UNLOCK</Text></TouchableOpacity> : null}<Text style={styles.time}>{new Date(signal.created_at).toLocaleString()}</Text></View>; }
function PublishModal({ visible, form, setForm, close, submit, saving }: { visible: boolean; form: typeof initial; setForm: React.Dispatch<React.SetStateAction<typeof initial>>; close: () => void; submit: () => void; saving: boolean }) { const set = (key: keyof typeof initial, value: string | boolean) => setForm(f => ({ ...f, [key]: value })); return <Modal visible={visible} transparent animationType="slide" onRequestClose={close}><View style={styles.overlay}><View style={styles.sheet}><View style={styles.modalHead}><Text style={styles.modalTitle}>Publish New Signal</Text><TouchableOpacity onPress={close}><Feather name="x" size={22} color="#FFF" /></TouchableOpacity></View><TextInput placeholder="Asset (e.g. BTCUSD)" placeholderTextColor="#707785" value={form.asset} onChangeText={v => set('asset', v)} style={styles.input} />{(['entry','takeProfit','stopLoss'] as const).map(k => <TextInput key={k} placeholder={k === 'takeProfit' ? 'Take profit' : k === 'stopLoss' ? 'Stop loss' : 'Entry'} placeholderTextColor="#707785" value={form[k]} keyboardType="decimal-pad" onChangeText={v => set(k, v)} style={styles.input} />)}<View style={styles.row}>{(['BUY','SELL'] as const).map(v => <TouchableOpacity key={v} onPress={() => set('direction', v)} style={[styles.choice, form.direction === v && styles.choiceOn]}><Text style={styles.choiceText}>{v}</Text></TouchableOpacity>)}</View><View style={styles.row}>{(['pending','active','won','lost'] as const).map(v => <TouchableOpacity key={v} onPress={() => set('status', v)} style={[styles.choice, form.status === v && styles.choiceOn]}><Text style={styles.choiceText}>{v.toUpperCase()}</Text></TouchableOpacity>)}</View><View style={styles.toggle}><Text style={styles.toggleText}>Premium signal</Text><Switch value={form.isPremium} onValueChange={v => set('isPremium', v)} trackColor={{ true: '#00F0FF' }} /></View><TouchableOpacity style={styles.publish} onPress={submit} disabled={saving}><Text style={styles.publishText}>{saving ? 'PUBLISHING…' : 'PUBLISH SIGNAL'}</Text></TouchableOpacity></View></View></Modal>; }
const styles = StyleSheet.create({ page:{flex:1,backgroundColor:'#0A0B0E',paddingTop:56},header:{paddingHorizontal:20,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},eyebrow:{color:'#00F0FF',fontSize:10,fontWeight:'900',letterSpacing:1.6},title:{color:'#FFF',fontSize:28,fontWeight:'900',marginTop:4},add:{width:44,height:44,borderRadius:22,backgroundColor:'#00F0FF',alignItems:'center',justifyContent:'center'},filters:{padding:20,gap:8},chip:{paddingHorizontal:14,paddingVertical:9,borderRadius:18,backgroundColor:'#191C22'},chipOn:{backgroundColor:'#00F0FF'},chipText:{color:'#9BA3AE',fontSize:12,fontWeight:'800'},chipTextOn:{color:'#071014'},list:{padding:20,paddingTop:0,gap:12},card:{backgroundColor:'#15181E',borderWidth:1,borderColor:'#292E38',borderRadius:16,padding:16},cardTop:{flexDirection:'row',justifyContent:'space-between'},asset:{color:'#FFF',fontWeight:'900',fontSize:19},direction:{fontWeight:'900',fontSize:12,marginTop:3},status:{color:'#AAB2BF',fontSize:10,fontWeight:'900',textAlign:'right'},badge:{color:'#FFD55A',fontSize:9,fontWeight:'900',marginTop:5},levels:{flexDirection:'row',justifyContent:'space-between',padding:14,backgroundColor:'#0D1015',borderRadius:10,marginTop:15},blur:{opacity:.18},label:{color:'#7C8490',fontSize:9,fontWeight:'900'},value:{color:'#FFF',fontSize:14,fontWeight:'800',marginTop:5},unlock:{backgroundColor:'#00F0FF',borderRadius:9,marginTop:12,padding:12,flexDirection:'row',justifyContent:'center',gap:7},unlockText:{color:'#071014',fontSize:10,fontWeight:'900'},time:{color:'#707785',fontSize:10,marginTop:12},center:{flex:1,alignItems:'center',justifyContent:'center',gap:10},muted:{color:'#8A929E',textAlign:'center'},error:{color:'#FF8692',textAlign:'center'},overlay:{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(0,0,0,.65)'},sheet:{backgroundColor:'#15181E',padding:20,borderTopLeftRadius:22,borderTopRightRadius:22,gap:10},modalHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:4},modalTitle:{color:'#FFF',fontSize:19,fontWeight:'900'},input:{backgroundColor:'#0B0D12',borderWidth:1,borderColor:'#2C313B',borderRadius:9,color:'#FFF',padding:13},row:{flexDirection:'row',gap:7},choice:{flex:1,padding:10,borderRadius:8,backgroundColor:'#242932',alignItems:'center'},choiceOn:{backgroundColor:'#276D76'},choiceText:{color:'#FFF',fontSize:10,fontWeight:'900'},toggle:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:5},toggleText:{color:'#FFF',fontWeight:'700'},publish:{backgroundColor:'#00F0FF',borderRadius:10,padding:15,alignItems:'center'},publishText:{color:'#071014',fontWeight:'900',fontSize:12} });