'use client';

import { Search } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';

type Post = { id: number; title: string; slug: string; excerpt: string; asset_class: 'Forex' | 'Crypto' | 'Stocks'; category: string; ai_badge: string; upvotes: number; published_at: string; tags: string[] };
const filters = ['All', 'Forex', 'Crypto', 'Stocks', 'Discussion', 'Analysis', 'Strategy', 'Psychology'] as const;

export default function Blog() {
  const [posts, setPosts] = useState<Post[]>([]);
  const [filter, setFilter] = useState<(typeof filters)[number]>('All');
  const [sort, setSort] = useState<'Hot' | 'New' | 'Top'>('Hot');
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('Loading live market intelligence…');
  useEffect(() => { (async () => { try { const res = await fetch('/api/posts?limit=50', { cache: 'no-store' }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setPosts(data.posts ?? []); setStatus(''); } catch (error) { setStatus(error instanceof Error ? error.message : 'Unable to load live insights.'); } })(); }, []);
  const visible = useMemo(() => posts.filter((post) => { const query = `${post.title} ${post.excerpt} ${post.category} ${post.asset_class} ${post.tags.join(' ')}`.toLowerCase(); return query.includes(search.toLowerCase()) && (filter === 'All' || post.asset_class === filter || post.category === filter); }).sort((a, b) => sort === 'Top' ? b.upvotes - a.upvotes : new Date(b.published_at).getTime() - new Date(a.published_at).getTime()), [posts, filter, sort, search]);
  return <main className="mx-auto max-w-5xl px-5 py-16 lg:px-8"><p className="text-xs font-bold uppercase tracking-[.25em] text-[#00FFFF]">Live market intelligence</p><h1 className="mt-4 text-4xl font-black tracking-tight text-white md:text-5xl">The institutional market room.</h1><div className="mt-7 flex items-center gap-2 rounded-xl border border-gray-800 bg-[#111111] px-4 py-3"><Search className="h-4 w-4 text-gray-500" /><input value={search} onChange={(e) => setSearch(e.target.value)} className="w-full bg-transparent text-sm outline-none" placeholder="Search insights, tags, or ticker symbols" /></div><div className="mt-5 flex flex-wrap gap-2">{filters.map((item) => <button onClick={() => setFilter(item)} key={item} className={`rounded-full border px-3 py-2 text-sm font-bold ${filter === item ? 'border-[#00FFFF] bg-[#00FFFF] text-black' : 'border-gray-800 bg-[#111111] text-gray-400'}`}>{item}</button>)}</div><div className="mt-3 flex gap-2">{(['Hot', 'New', 'Top'] as const).map((item) => <button onClick={() => setSort(item)} key={item} className={`rounded-lg px-3 py-2 text-sm ${sort === item ? 'bg-white/10 text-white' : 'text-gray-500'}`}>{item === 'Hot' ? '🔥 Hot' : item === 'New' ? '⚡ New' : '🏆 Top'}</button>)}</div>{status && <p className="mt-7 text-sm text-gray-400">{status}</p>}<div className="mt-7 grid gap-4">{visible.map((post) => <article className="rounded-2xl border border-gray-800 bg-[#111111] p-5" key={post.id}><div className="flex flex-wrap gap-2 text-xs font-bold"><span className="text-[#00FFFF]">{post.asset_class}</span><span className="text-gray-500">· {post.category}</span><span className="text-gray-500">· {new Date(post.published_at).toLocaleDateString()}</span></div><h2 className="mt-3 text-xl font-bold text-white">{post.title}</h2><p className="mt-3 leading-7 text-gray-400">{post.excerpt}</p><div className="mt-4 flex flex-wrap items-center gap-3"><span className="rounded-full border border-[#00FFFF]/30 bg-[#00FFFF]/10 px-2.5 py-1 text-[10px] font-extrabold text-[#00FFFF]">{post.ai_badge || '⚡ AI INSIGHT'}</span><span className="text-xs text-gray-500">▲ {post.upvotes} · Comments · Share</span></div></article>)}{!visible.length && !status && <div className="rounded-2xl border border-gray-800 bg-[#111111] p-8 text-gray-400">No published insights match your filters yet.</div>}</div></main>;
}