import React, { useState } from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { Stack } from 'expo-router';

const CYAN = '#00F0FF';
const lessons = ['How to Trade AI Confluence', 'Risk Management 101', 'Reading Institutional Flow'];
const glossary = [
  ['Order Block', 'A zone where institutional orders accumulated before a strong market displacement.'],
  ['Liquidity Sweep', 'A temporary move through obvious highs or lows that collects resting orders before reversing.'],
  ['Fair Value Gap (FVG)', 'An imbalance between candles that price may revisit as the market seeks efficient delivery.'],
] as const;

export default function AppGuideScreen() {
  const [open, setOpen] = useState<number | null>(null);
  return <View style={styles.container}><Stack.Screen options={{ title: 'TradiQs Academy', headerShown: true, headerStyle: { backgroundColor: '#0A0B0E' }, headerTintColor: '#FFF' }} /><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>TRADIQS ACADEMY</Text><Text style={styles.title}>Build your edge.</Text><View style={styles.progressCard}><View style={styles.progressHeader}><Text style={styles.progressTitle}>Bootcamp Completion</Text><Text style={styles.percent}>0%</Text></View><View style={styles.track}><View style={styles.fill} /></View><Text style={styles.muted}>Start with the foundations of disciplined execution.</Text></View><Text style={styles.section}>VIDEO LESSONS</Text>{lessons.map((lesson, index) => <TouchableOpacity key={lesson} style={styles.lesson} activeOpacity={0.85}><View style={styles.play}><Feather name="play" size={18} color={CYAN} /></View><View style={styles.lessonCopy}><Text style={styles.lessonTitle}>{lesson}</Text><Text style={styles.muted}>{index === 0 ? '12 min lesson' : index === 1 ? '9 min lesson' : '14 min lesson'}</Text></View><Feather name="lock" size={15} color="#737983" /></TouchableOpacity>)}<Text style={styles.section}>TRADING GLOSSARY</Text>{glossary.map(([term, definition], index) => <View key={term} style={styles.glossary}><TouchableOpacity onPress={() => setOpen(open === index ? null : index)} style={styles.glossaryHeader}><Text style={styles.term}>{term}</Text><Feather name="chevron-down" size={17} color={CYAN} style={{ transform: [{ rotate: open === index ? '180deg' : '0deg' }] }} /></TouchableOpacity>{open === index && <Text style={styles.definition}>{definition}</Text>}</View>)}</ScrollView></View>;
}

const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#0A0B0E' }, content: { padding: 20, paddingBottom: 40 }, eyebrow: { color: CYAN, fontSize: 10, fontWeight: '700', letterSpacing: 2 }, title: { color: '#FFF', fontSize: 28, fontWeight: '700', marginTop: 8 }, progressCard: { backgroundColor: '#16181D', borderRadius: 15, borderWidth: 1, borderColor: '#262930', padding: 17, marginTop: 22 }, progressHeader: { flexDirection: 'row', justifyContent: 'space-between' }, progressTitle: { color: '#FFF', fontSize: 14, fontWeight: '700' }, percent: { color: CYAN, fontSize: 15, fontWeight: '700' }, track: { height: 8, borderRadius: 4, backgroundColor: '#30343D', overflow: 'hidden', marginTop: 15 }, fill: { width: '0%', height: '100%', backgroundColor: CYAN }, muted: { color: '#737983', fontSize: 11, marginTop: 9 }, section: { color: '#6D727B', fontSize: 10, fontWeight: '700', letterSpacing: 1.5, marginTop: 28, marginBottom: 10 }, lesson: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#16181D', borderRadius: 13, borderWidth: 1, borderColor: '#262930', padding: 13, marginBottom: 9 }, play: { width: 44, height: 44, borderRadius: 10, backgroundColor: 'rgba(0,240,255,.1)', alignItems: 'center', justifyContent: 'center' }, lessonCopy: { flex: 1, marginLeft: 12 }, lessonTitle: { color: '#FFF', fontSize: 13, fontWeight: '700' }, glossary: { backgroundColor: '#16181D', borderRadius: 12, borderWidth: 1, borderColor: '#262930', marginBottom: 8, paddingHorizontal: 14 }, glossaryHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', minHeight: 53 }, term: { color: '#FFF', fontSize: 13, fontWeight: '700' }, definition: { color: '#9A9FA8', fontSize: 12, lineHeight: 18, paddingBottom: 14 } });