import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Modal, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { Stack } from 'expo-router';
import { ApiError, customFetch } from '@workspace/api-client-react';

type Bot = { id: string; pair: string; strategy: 'GRID' | 'DCA'; capital: number; status: 'active' | 'paused'; pnl: number; created_at: string };
const fresh = { pair: 'BTC/USD', strategy: 'GRID' as Bot['strategy'], capital: '' };
export default function AutoPilotScreen() {
  const [bots, setBots] = useState<Bot[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [open, setOpen] = useState(false); const [form, setForm] = useState(fresh); const [saving, setSaving] = useState(false);
  const apiUrl = process.env.EXPO_PUBLIC_API_URL ?? '(no API URL configured)';
  const load = useCallback(async () => { setLoading(true); setError(''); try { const data = await customFetch<unknown>('/api/bots'); setBots(Array.isArray(data) ? data as Bot[] : []); if (!Array.isArray(data)) setError('HTTP 200: Failed to parse JSON.'); } catch (caught) { console.error('[AutoPilot Fetch Error]:', caught); const detail = caught instanceof ApiError && caught.status === 401 ? 'HTTP 401: Your session is missing or expired. Please sign in again.' : caught instanceof ApiError ? `HTTP ${caught.status}: ${caught.message || 'Failed to parse JSON.'}` : caught instanceof Error ? `${caught.name}: ${caught.message}` : String(caught); setBots([]); setError(detail); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const active = bots.filter(b => b.status === 'active'); const capital = bots.reduce((sum,b) => sum + Number(b.capital || 0), 0); const pnl = bots.reduce((sum,b) => sum + Number(b.pnl || 0), 0);
  const deploy = async () => { const capitalValue = Number(form.capital); if (!capitalValue || capitalValue <= 0) return setError('Enter a valid virtual capital amount.'); setSaving(true); try { await customFetch('/api/bots', { method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pair:form.pair,strategy:form.strategy,capital:capitalValue}) }); setOpen(false); setForm(fresh); await load(); } catch { setError('Unable to deploy bot. Check that the latest Supabase migration is applied.'); } finally { setSaving(false); } };
  const toggle = async (bot: Bot) => { try { const updated = await customFetch<Bot>(`/api/bots/${bot.id}/status`, { method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:bot.status === 'active' ? 'paused':'active'}) }); setBots(list => list.map(b => b.id === updated.id ? updated : b)); } catch { setError('Unable to update this bot.'); } };
  return <View style={s.page}><Stack.Screen options={{ title:'AutoPilot Bots',headerStyle:{backgroundColor:'#0A0B0E'},headerTintColor:'#FFF' }}/><ScrollView contentContainerStyle={s.content}><View style={s.head}><View><Text style={s.eyebrow}>PAPER TRADING ENGINE</Text><Text style={s.title}>AutoPilot Bots</Text></View><TouchableOpacity style={s.deploy} onPress={() => setOpen(true)}><Feather name="plus" size={17} color="#071014"/><Text style={s.deployText}>DEPLOY</Text></TouchableOpacity></View><Text style={s.copy}>Automate your simulated strategies with cloud-managed virtual capital.</Text><View style={s.summary}>{[['ACTIVE BOTS',active.length],['CAPITAL DEPLOYED',`$${capital.toLocaleString()}`],['TOTAL PNL',`${pnl >= 0 ? '+' : ''}$${pnl.toFixed(2)}`]].map(([label,value])=><View key={String(label)} style={s.stat}><Text style={s.statLabel}>{label}</Text><Text style={[s.statValue,label === 'TOTAL PNL' && pnl < 0 ? s.loss : s.gain]}>{value}</Text></View>)}</View>{loading?<View style={s.center}><ActivityIndicator color="#00F0FF"/><Text style={s.muted}>Loading bots…</Text></View>:<View style={s.list}>{error?<TouchableOpacity onPress={load}><Text style={s.error}>Tried fetching: {apiUrl}/api/bots{'\n'}{error}{'\n'}Tap to retry.</Text></TouchableOpacity>:null}{bots.map(bot=><View key={bot.id} style={s.card}><View style={s.cardHead}><View><Text style={s.pair}>{bot.pair}</Text><Text style={s.strategy}>{bot.strategy} STRATEGY</Text></View><Switch value={bot.status==='active'} onValueChange={()=>toggle(bot)} trackColor={{true:'#00F0FF'}}/></View><View style={s.metrics}><Metric label="CAPITAL" value={`$${Number(bot.capital).toLocaleString()}`}/><Metric label="LIVE PNL" value={`${Number(bot.pnl)>=0?'+':''}$${Number(bot.pnl).toFixed(2)}`} good={Number(bot.pnl)>=0}/><Metric label="STATUS" value={bot.status.toUpperCase()} good={bot.status==='active'}/></View></View>)}{!bots.length&&!error?<Text style={s.muted}>No active bots deployed</Text>:null}</View>}</ScrollView><DeployModal visible={open} form={form} setForm={setForm} close={()=>setOpen(false)} submit={deploy} saving={saving}/></View>;
}
function Metric({label,value,good}:{label:string;value:string;good?:boolean}){return <View><Text style={s.statLabel}>{label}</Text><Text style={[s.metric,good===false&&s.loss,good===true&&s.gain]}>{value}</Text></View>}
function DeployModal({visible,form,setForm,close,submit,saving}:{visible:boolean;form:typeof fresh;setForm:React.Dispatch<React.SetStateAction<typeof fresh>>;close:()=>void;submit:()=>void;saving:boolean}){return <Modal visible={visible} transparent animationType="slide" onRequestClose={close}><View style={s.overlay}><View style={s.sheet}><View style={s.modalHead}><Text style={s.modalTitle}>Deploy New Bot</Text><TouchableOpacity onPress={close}><Feather name="x" size={22} color="#FFF"/></TouchableOpacity></View><Text style={s.field}>TRADING PAIR</Text><View style={s.options}>{(['BTC/USD','EUR/USD','XAU/USD'] as const).map(pair=><TouchableOpacity key={pair} onPress={()=>setForm(f=>({...f,pair}))} style={[s.option,form.pair===pair&&s.optionOn]}><Text style={s.optionText}>{pair}</Text></TouchableOpacity>)}</View><Text style={s.field}>STRATEGY</Text><View style={s.options}>{(['GRID','DCA'] as const).map(strategy=><TouchableOpacity key={strategy} onPress={()=>setForm(f=>({...f,strategy}))} style={[s.option,form.strategy===strategy&&s.optionOn]}><Text style={s.optionText}>{strategy}</Text></TouchableOpacity>)}</View><TextInput value={form.capital} onChangeText={capital=>setForm(f=>({...f,capital}))} keyboardType="decimal-pad" placeholder="Virtual capital (USD)" placeholderTextColor="#777F8B" style={s.input}/><TouchableOpacity style={s.submit} onPress={submit} disabled={saving}><Text style={s.submitText}>{saving?'DEPLOYING…':'DEPLOY PAPER BOT'}</Text></TouchableOpacity></View></View></Modal>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#0A0B0E'},content:{padding:20,paddingBottom:42},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},eyebrow:{color:'#00F0FF',fontSize:10,fontWeight:'900',letterSpacing:1.5},title:{color:'#FFF',fontSize:27,fontWeight:'900',marginTop:5},deploy:{backgroundColor:'#00F0FF',borderRadius:9,padding:11,flexDirection:'row',gap:5,alignItems:'center'},deployText:{color:'#071014',fontWeight:'900',fontSize:10},copy:{color:'#9098A5',lineHeight:19,marginTop:10},summary:{flexDirection:'row',gap:8,marginTop:20},stat:{flex:1,backgroundColor:'#15181E',borderRadius:10,padding:11},statLabel:{color:'#77808D',fontSize:8,fontWeight:'900'},statValue:{color:'#FFF',fontWeight:'900',fontSize:13,marginTop:6},gain:{color:'#27D68A'},loss:{color:'#FF6576'},list:{gap:10,marginTop:18},card:{backgroundColor:'#15181E',borderRadius:14,borderWidth:1,borderColor:'#2B3039',padding:15},cardHead:{flexDirection:'row',justifyContent:'space-between'},pair:{color:'#FFF',fontSize:19,fontWeight:'900'},strategy:{color:'#00F0FF',fontSize:10,fontWeight:'900',marginTop:4},metrics:{marginTop:15,paddingTop:14,borderTopWidth:1,borderTopColor:'#292E36',flexDirection:'row',justifyContent:'space-between'},metric:{color:'#FFF',fontSize:12,fontWeight:'800',marginTop:5},center:{padding:40,alignItems:'center',gap:12},muted:{color:'#8B94A1',textAlign:'center',marginTop:18},error:{color:'#FF8090',textAlign:'center',marginTop:18},overlay:{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(0,0,0,.7)'},sheet:{backgroundColor:'#15181E',borderTopLeftRadius:22,borderTopRightRadius:22,padding:20,gap:10},modalHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:5},modalTitle:{color:'#FFF',fontSize:19,fontWeight:'900'},field:{color:'#88919E',fontSize:9,fontWeight:'900',marginTop:6},options:{flexDirection:'row',gap:7},option:{flex:1,backgroundColor:'#242932',borderRadius:8,padding:11,alignItems:'center'},optionOn:{backgroundColor:'#276D76'},optionText:{color:'#FFF',fontWeight:'800',fontSize:11},input:{color:'#FFF',backgroundColor:'#0C0E13',borderRadius:9,borderWidth:1,borderColor:'#303641',padding:14,marginTop:5},submit:{backgroundColor:'#00F0FF',borderRadius:10,padding:15,alignItems:'center',marginTop:7},submitText:{color:'#071014',fontWeight:'900',fontSize:11}});