import React, { useEffect, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as SecureStore from 'expo-secure-store';
import { Modal, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { Stack } from 'expo-router';

const CYAN = '#00F0FF';
type Field = 'API Key' | 'API Secret' | 'Account ID' | 'Password' | 'Server Name' | 'Platform';
type Broker = { name: string; category: string; fields: Field[] };
const BROKERS: Broker[] = [
  ...['Binance','Bybit','Coinbase','OKX','KuCoin'].map(name => ({ name, category:'Crypto', fields:['API Key','API Secret'] as Field[] })),
  ...['MetaTrader 4','MetaTrader 5','Exness','Oanda','IC Markets'].map(name => ({ name, category:'Forex & CFDs', fields:['Account ID','Password','Server Name'] as Field[] })),
  ...['Interactive Brokers','Webull','TradeStation'].map(name => ({ name, category:'Stocks', fields:['API Key','API Secret'] as Field[] })),
  ...['FTMO','Topstep'].map(name => ({ name, category:'Prop Firms', fields:['Account ID','Password','Platform'] as Field[] })),
];
const keyFor = (name: string) => `tradiqs.broker-sync.${name.toLowerCase().replace(/\W+/g,'-')}`;
const storage = { get: (key:string) => Platform.OS === 'web' ? AsyncStorage.getItem(key) : SecureStore.getItemAsync(key), set: (key:string, value:string) => Platform.OS === 'web' ? AsyncStorage.setItem(key,value) : SecureStore.setItemAsync(key,value), remove: (key:string) => Platform.OS === 'web' ? AsyncStorage.removeItem(key) : SecureStore.deleteItemAsync(key) };

export default function BrokerSyncScreen() {
  const [connected, setConnected] = useState<Record<string, boolean>>({}); const [broker, setBroker] = useState<Broker | null>(null); const [values, setValues] = useState<Record<string,string>>({});
  const refresh = async () => { const entries = await Promise.all(BROKERS.map(async b => [b.name, Boolean(await storage.get(keyFor(b.name)))] as const)); setConnected(Object.fromEntries(entries)); };
  useEffect(() => { void refresh(); }, []);
  const open = (b:Broker) => { setBroker(b); setValues({}); };
  const save = async () => { if (!broker || !broker.fields.every(f => values[f]?.trim())) return; await storage.set(keyFor(broker.name), JSON.stringify(values)); setConnected(x=>({...x,[broker.name]:true})); setBroker(null); };
  const disconnect = async () => { if (!broker) return; await storage.remove(keyFor(broker.name)); setConnected(x=>({...x,[broker.name]:false})); setBroker(null); };
  return <View style={s.page}><Stack.Screen options={{ title:'Exchange Integration',headerStyle:{backgroundColor:'#0A0B0E'},headerTintColor:'#FFF' }}/><ScrollView contentContainerStyle={s.content}><Text style={s.kicker}>BROKERSYNC</Text><Text style={s.title}>Exchange Integration</Text><Text style={s.copy}>Securely connect accounts on this device for account tracking and signal insights.</Text>{['Crypto','Forex & CFDs','Stocks','Prop Firms'].map(category=><View key={category}><Text style={s.section}>{category.toUpperCase()}</Text>{BROKERS.filter(b=>b.category===category).map(b=><TouchableOpacity key={b.name} style={s.card} onPress={()=>open(b)}><View style={s.left}><View style={s.icon}><Feather name="bar-chart-2" size={18} color={CYAN}/></View><View><Text style={s.name}>{b.name}</Text><Text style={s.sub}>{connected[b.name]?'Connection active':'Not connected'}</Text></View></View><View style={connected[b.name]?s.badge:s.badgeOff}><Text style={connected[b.name]?s.badgeText:s.badgeOffText}>{connected[b.name]?'CONNECTED':'UNLINKED'}</Text></View></TouchableOpacity>)}</View>)}</ScrollView><Modal visible={!!broker} transparent animationType="slide" onRequestClose={()=>setBroker(null)}><View style={s.overlay}><View style={s.sheet}><View style={s.head}><View><Text style={s.kicker}>{broker?.category.toUpperCase()}</Text><Text style={s.modalTitle}>{broker?.name}</Text></View><TouchableOpacity onPress={()=>setBroker(null)}><Feather name="x" size={22} color="#FFF"/></TouchableOpacity></View>{connected[broker?.name ?? ''] ? <><Text style={s.copy}>This connection is stored securely on this device.</Text><TouchableOpacity style={s.disconnect} onPress={()=>void disconnect()}><Text style={s.disconnectText}>DISCONNECT</Text></TouchableOpacity></> : <>{broker?.fields.map(field=><TextInput key={field} value={values[field]??''} onChangeText={v=>setValues(x=>({...x,[field]:v}))} placeholder={field} placeholderTextColor="#77808D" secureTextEntry={field==='Password'||field==='API Secret'} autoCapitalize="none" style={s.input}/>) }<Text style={s.note}>Credentials are stored locally using encrypted device storage.</Text><TouchableOpacity style={[s.connect,!broker?.fields.every(f=>values[f]?.trim())&&s.disabled]} onPress={()=>void save()}><Text style={s.connectText}>CONNECT SECURELY</Text></TouchableOpacity></>}</View></View></Modal></View>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#0A0B0E'},content:{padding:20,paddingBottom:48},kicker:{color:CYAN,fontSize:10,fontWeight:'900',letterSpacing:1.5},title:{color:'#FFF',fontSize:27,fontWeight:'900',marginTop:7},copy:{color:'#9098A5',lineHeight:19,marginTop:8},section:{color:'#77808D',fontSize:10,fontWeight:'900',letterSpacing:1.4,marginTop:26,marginBottom:9},card:{backgroundColor:'#15181E',borderWidth:1,borderColor:'#2B3039',borderRadius:12,padding:13,marginBottom:8,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},left:{flexDirection:'row',gap:11,alignItems:'center'},icon:{width:35,height:35,borderRadius:9,alignItems:'center',justifyContent:'center',backgroundColor:'#0D2026'},name:{color:'#FFF',fontWeight:'800',fontSize:14},sub:{color:'#7E8794',fontSize:11,marginTop:3},badge:{backgroundColor:'#113D2A',paddingHorizontal:8,paddingVertical:5,borderRadius:6},badgeOff:{backgroundColor:'#272B32',paddingHorizontal:8,paddingVertical:5,borderRadius:6},badgeText:{color:'#5FF0A2',fontSize:9,fontWeight:'900'},badgeOffText:{color:'#99A1AC',fontSize:9,fontWeight:'900'},overlay:{flex:1,justifyContent:'flex-end',backgroundColor:'#000B'},sheet:{backgroundColor:'#15181E',padding:20,paddingBottom:38,borderTopLeftRadius:22,borderTopRightRadius:22},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},modalTitle:{color:'#FFF',fontSize:21,fontWeight:'900',marginTop:4},input:{color:'#FFF',backgroundColor:'#0C0E12',borderWidth:1,borderColor:'#303641',borderRadius:9,padding:13,marginTop:12},note:{color:'#7E8794',fontSize:11,lineHeight:16,marginTop:12},connect:{backgroundColor:CYAN,padding:15,borderRadius:10,alignItems:'center',marginTop:16},disabled:{opacity:.45},connectText:{color:'#071014',fontWeight:'900',fontSize:11},disconnect:{borderWidth:1,borderColor:'#FF6576',padding:15,borderRadius:10,alignItems:'center',marginTop:22},disconnectText:{color:'#FF6576',fontWeight:'900',fontSize:11}});