import React, { useState } from 'react';
import { Linking, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { Stack } from 'expo-router';

const CYAN = '#00F0FF';
const faqs = [
  ['My simulated PnL is wrong', 'PnL is calculated from the recorded entry and live close price. Refresh your Portfolio after closing a position to sync the latest result.'],
  ['How do I upgrade to Elite?', 'Open the subscription panel from your Profile and choose an eligible plan. Elite access unlocks the highest signal and support tier.'],
  ['What timezone are signals in?', 'Signal timestamps are shown in UTC by default. You can choose your preferred trading-day timezone from Profile settings.'],
] as const;

export default function HelpCenterScreen() {
  const [open, setOpen] = useState<number | null>(null);
  return <View style={styles.container}><Stack.Screen options={{ title: 'VIP Support', headerShown: true, headerStyle: { backgroundColor: '#0A0B0E' }, headerTintColor: '#FFF' }} /><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>CONCIERGE DESK</Text><Text style={styles.title}>VIP Support</Text><Text style={styles.intro}>Institutional-grade assistance when every decision matters.</Text><View style={styles.statusCard}><Text style={styles.sectionTitle}>SYSTEM STATUS</Text>{['AI Signal Engine: Operational', 'Trade Execution: Optimal', 'Database: Connected'].map((item) => <View key={item} style={styles.statusRow}><View style={styles.dot} /><Text style={styles.statusText}>{item}</Text><Text style={styles.live}>LIVE</Text></View>)}</View><TouchableOpacity style={styles.ticket} onPress={() => Linking.openURL('mailto:support@tradiqsai.com')} activeOpacity={0.85}><Feather name="message-circle" size={22} color="#0A0B0E" /><Text style={styles.ticketTitle}>Open Support Ticket</Text><Text style={styles.ticketSub}>Elite tier members receive guaranteed 1-hour response times.</Text></TouchableOpacity><Text style={styles.section}>FREQUENTLY ASKED QUESTIONS</Text>{faqs.map(([question, answer], index) => <View key={question} style={styles.faq}><TouchableOpacity style={styles.faqHeader} onPress={() => setOpen(open === index ? null : index)}><Text style={styles.question}>{question}</Text><Feather name="chevron-down" size={17} color={CYAN} style={{ transform: [{ rotate: open === index ? '180deg' : '0deg' }] }} /></TouchableOpacity>{open === index && <Text style={styles.answer}>{answer}</Text>}</View>)}</ScrollView></View>;
}

const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#0A0B0E' }, content: { padding: 20, paddingBottom: 40 }, eyebrow: { color: CYAN, fontSize: 10, fontWeight: '700', letterSpacing: 2 }, title: { color: '#FFF', fontSize: 28, fontWeight: '700', marginTop: 8 }, intro: { color: '#8A8D93', fontSize: 13, lineHeight: 19, marginTop: 7 }, statusCard: { backgroundColor: '#16181D', borderRadius: 15, borderWidth: 1, borderColor: '#262930', padding: 16, marginTop: 22 }, sectionTitle: { color: '#6D727B', fontSize: 10, fontWeight: '700', letterSpacing: 1.5, marginBottom: 10 }, statusRow: { flexDirection: 'row', alignItems: 'center', minHeight: 34 }, dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#2ECA8B', marginRight: 10 }, statusText: { color: '#FFF', fontSize: 12, flex: 1 }, live: { color: '#2ECA8B', fontSize: 9, fontWeight: '700', letterSpacing: 1 }, ticket: { backgroundColor: CYAN, borderRadius: 15, padding: 19, marginTop: 16 }, ticketTitle: { color: '#0A0B0E', fontSize: 18, fontWeight: '700', marginTop: 12 }, ticketSub: { color: '#16464B', fontSize: 11, lineHeight: 16, marginTop: 5 }, section: { color: '#6D727B', fontSize: 10, fontWeight: '700', letterSpacing: 1.5, marginTop: 28, marginBottom: 10 }, faq: { backgroundColor: '#16181D', borderRadius: 12, borderWidth: 1, borderColor: '#262930', marginBottom: 8, paddingHorizontal: 14 }, faqHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', minHeight: 54 }, question: { color: '#FFF', fontSize: 13, fontWeight: '700', flex: 1, paddingRight: 12 }, answer: { color: '#9A9FA8', fontSize: 12, lineHeight: 18, paddingBottom: 14 } });